### ISSUE TITLE
PyPI Update

### ISSUE THREAD

**Issue by paulrogozenski** [cmbant/getdist#87] opened 2022-11-16 15:18 UTC
When will the newest version of getdist be up on PyPI? Currently, the newest version there is 1.3.4 and does not supply integration with PySide6 like 1.4 does. I'm having installation issues on Linux regarding permissions when installing from the source files and could use this update.

**Comment by paulrogozenski** [comment] 2022-11-16 16:52
Thank you for posting the update so quickly! I'm running into some errors when running the test and running the gui. They are attached below. Do you know what would be causing this? Thank you!

$ python -m unittest getdist.tests.getdist_test
..Removed no burn in
Removed no burn in
Removed no burn in
/tmp/gettdist_tests/testchain_1.txt
WARNING:root:Install pandas for faster reading from text files
/tmp/gettdist_tests/testchain_3.txt
/tmp/gettdist_tests/testchain_2.txt
Removed 0.1 as burn in
/home/paul/.local/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py:136: DeprecationWarning: Enum value 'Qt::ApplicationAttribute.AA_EnableHighDpiScaling' is marked as deprecated, please check the documentation for more information.
  QtWidgets.QApplication.setAttribute(
/home/paul/.local/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py:154: DeprecationWarning: Enum value 'Qt::ApplicationAttribute.AA_UseHighDpiPixmaps' is marked as deprecated, please check the documentation for more information.
  app.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps)  # Only for Qt<6.
.Removed no burn in
Removed no burn in
Removed no burn in
producing files in directory  ./
/tmp/gettdist_tests/testchain_1.txt
/tmp/gettdist_tests/testchain_3.txt
/tmp/gettdist_tests/testchain_2.txt
Removed no burn in
Number of chains used =  3
 var(mean)/mean(var), remaining chains, worst e-value: R-1 =       0.00077
RL: Thin for Markov:  1
RL: Thin for indep samples:   1
RL: Estimated burn in steps:  2  ( 2  rows)
using 12000 rows, 2 parameters; mean weight 1.0, tot weight 12000.0
Approx indep samples (N/corr length): 12001
Equiv number of single samples (sum w)/max(w): 12000
Effective number of weighted samples (sum w)^2/sum(w^2): 12000
Best fit sample -log(Like) = 1.708504
Ln(mean 1/like) = 3.497050
mean(-Ln(like)) = 2.568060
-Ln(mean like)  = 2.318792
Template .ini file written to testchain_pars.ini
/tmp/gettdist_tests/testchain_1.txt
/tmp/gettdist_tests/testchain_3.txt
/tmp/gettdist_tests/testchain_2.txt
Removed no burn in
Number of chains used =  3
 var(mean)/mean(var), remaining chains, worst e-value: R-1 =       0.00077
RL: Thin for Markov:  1
RL: Thin for indep samples:   1
RL: Estimated burn in steps:  2  ( 2  rows)
using 12000 rows, 2 parameters; mean weight 1.0, tot weight 12000.0
Approx indep samples (N/corr length): 12001
Equiv number of single samples (sum w)/max(w): 12000
Effective number of weighted samples (sum w)^2/sum(w^2): 12000
Best fit sample -log(Like) = 1.708504
Ln(mean 1/like) = 3.497050
mean(-Ln(like)) = 2.568060
-Ln(mean like)  = 2.318792
...producing 2D plots
...producing triangle plot
...producing  1 2D colored scatter plots
ERemoved no burn in
.Removed no burn in
Removed no burn in
Removed no burn in
Removed no burn in
Removed no burn in
.Removed no burn in
Removed no burn in
.Removed no burn in
Removed no burn in
Removed no burn in
Removed no burn in
.Removed no burn in
.Removed no burn in
WARNING:root:fine_bins_2D not large enough for optimal density: x, y
.Removed no burn in
.Removed no burn in
/home/paul/.local/lib/python3.10/site-packages/getdist/plots.py:2843: UserWarning: No data for colormapping provided via 'c'. Parameters 'cmap' will be ignored
  self.last_scatter = ax.scatter(samples[0], samples[1], edgecolors='none',
Removed no burn in
.Removed no burn in
....Removed no burn in
..
======================================================================
ERROR: testGetDist (getdist.tests.getdist_test.GetDistFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/.local/lib/python3.10/site-packages/getdist/tests/getdist_test.py", line 88, in testGetDist
    check_run()
  File "/home/paul/.local/lib/python3.10/site-packages/getdist/tests/getdist_test.py", line 82, in check_run
    subprocess.check_output(['python', pyname])
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'

----------------------------------------------------------------------
Ran 18 tests in 37.513s

FAILED (errors=1)

$ getdist-gui
Traceback (most recent call last):
  File "/home/paul/.local/bin/getdist-gui", line 8, in <module>
    sys.exit(getdist_gui())
  File "/home/paul/.local/lib/python3.10/site-packages/getdist/command_line.py", line 355, in getdist_gui
    run_gui()
  File "/home/paul/.local/lib/python3.10/site-packages/getdist/gui/mainwindow.py", line 2362, in run_gui
    mainWin = MainWindow(app, ini=args.ini, plot_scale=args.plot_scale)
  File "/home/paul/.local/lib/python3.10/site-packages/getdist/gui/mainwindow.py", line 159, in __init__
    self._createWidgets()
  File "/home/paul/.local/lib/python3.10/site-packages/getdist/gui/mainwindow.py", line 415, in _createWidgets
    self.listRoots = RootListWidget(self.selectWidget, self)
  File "/home/paul/.local/lib/python3.10/site-packages/getdist/gui/mainwindow.py", line 115, in __init__
    self.setDragDropMode(self.InternalMove)
AttributeError: 'RootListWidget' object has no attribute 'InternalMove'

**Comment by cmbant** [comment] 2022-11-16 17:20
Not sure why it's giving an error, but you can probably comment the self.setDragDropMode(self.InternalMove) line?

Looks like you don't have "python" on your path to run python?

Looks as though you are trying to produce a 3d plot, but have only 2 parameters giving the cmap error.

**Comment by cmbant** [comment] 2023-01-11 09:22
I have changed the InternalMove line in https://github.com/cmbant/getdist/commit/84ba8037bf095bb5814507256b0fdc1cb0cd04fe. Closing, but can reopen if any other issue is reproducible.

**Closed by cmbant** 2023-01-11 09:22 UTC
